pub mod aggregator;
mod csv_parser;
mod importer;
pub mod market_stats;
pub mod vci;
pub mod ticker_fetcher;
pub mod data_sync;
pub mod csv_enhancer;
pub mod csv_validator;
pub mod data_store;
pub mod trading_hours;
pub mod api_logging;
pub mod crypto_compare;

pub use aggregator::Aggregator;
pub use importer::import_legacy;
pub use market_stats::{get_market_stats, get_ticker_info, is_index, MarketStats, TickerInfo, TimeframeInfo};
pub use vci::{VciClient, VciError, OhlcvData, CompanyInfo};
pub use ticker_fetcher::TickerFetcher;
pub use data_sync::DataSync;
pub use csv_enhancer::{enhance_interval, enhance_data, EnhancementStats, save_enhanced_csv_to_dir};
pub use csv_validator::{validate_and_repair_interval, CorruptionReport};
pub use data_store::{DataStore, SharedDataStore, HealthStats, SharedHealthStats, estimate_memory_usage};
pub use trading_hours::{is_trading_hours, get_sync_interval};
pub use api_logging::{ApiPerformanceMetrics, ApiStatus, DataSource, write_api_log_entry, determine_data_source};
pub use crypto_compare::{CryptoCompareClient, CryptoError};
