"""
Analyze company_info.json generated by `aipriceaction generate-company-info --save`.

Usage:
    python scripts/analyze_company_info.py [path/to/company_info.json]
"""

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

def load_data(path: str) -> list[dict]:
    p = Path(path)
    if not p.exists():
        print(f"ERROR: {path} not found")
        sys.exit(1)
    with open(p, "r", encoding="utf-8") as f:
        return json.load(f)


def fmt_vnd(value: float | None) -> str:
    if value is None:
        return "N/A"
    if abs(value) >= 1e12:
        return f"{value / 1e12:,.1f}T VND"
    if abs(value) >= 1e9:
        return f"{value / 1e9:,.1f}B VND"
    if abs(value) >= 1e6:
        return f"{value / 1e6:,.1f}M VND"
    return f"{value:,.0f} VND"


def fmt_pct(value: float | None) -> str:
    if value is None:
        return "N/A"
    return f"{value * 100:.2f}%"


def fmt_number(value: float | None) -> str:
    if value is None:
        return "N/A"
    return f"{value:,.2f}"


# ── Section 1: Overview ──────────────────────────────────────────────────────

def section_overview(data: list[dict]):
    total = len(data)
    has_info = [d for d in data if d.get("company_info")]
    has_ratios = [d for d in data if d.get("financial_ratios")]
    empty = [d for d in data if not d.get("company_info") and not d.get("financial_ratios")]

    print("=" * 70)
    print("SECTION 1: OVERVIEW")
    print("=" * 70)
    print(f"  Total tickers:              {total}")
    print(f"  With company_info:          {len(has_info)} ({len(has_info)/total*100:.1f}%)")
    print(f"  With financial_ratios:      {len(has_ratios)} ({len(has_ratios)/total*100:.1f}%)")
    print(f"  Completely empty:           {len(empty)} ({len(empty)/total*100:.1f}%)")

    if empty:
        print(f"\n  Empty tickers ({len(empty)}):")
        for d in empty[:30]:
            name = d.get("name") or ""
            label = f"  - {d['ticker']}"
            if name:
                label += f" ({name})"
            print(label)
        if len(empty) > 30:
            print(f"  ... and {len(empty) - 30} more")

    print()


# ── Section 2: Exchange & Industry Distribution ─────────────────────────────

def section_exchange_industry(data: list[dict]):
    has_info = [d for d in data if d.get("company_info")]

    exchanges = Counter()
    industries = Counter()
    for d in has_info:
        ci = d["company_info"]
        exchanges[ci.get("exchange") or "UNKNOWN"] += 1
        industries[ci.get("industry") or "UNKNOWN"] += 1

    print("=" * 70)
    print("SECTION 2: EXCHANGE & INDUSTRY DISTRIBUTION")
    print("=" * 70)

    print("\n  Exchanges:")
    for ex, count in exchanges.most_common():
        print(f"    {ex or 'N/A':<15} {count:>4} tickers")

    print(f"\n  Industries ({len(industries)} unique):")
    for ind, count in industries.most_common(20):
        print(f"    {ind:<45} {count:>3}")
    if len(industries) > 20:
        print(f"    ... and {len(industries) - 20} more")

    print()


# ── Section 3: Market Cap Distribution ──────────────────────────────────────

def section_market_cap(data: list[dict]):
    has_info = [d for d in data if d.get("company_info")]

    caps = []
    for d in has_info:
        ci = d["company_info"]
        mc = ci.get("market_cap")
        if mc and mc > 0:
            caps.append((d["ticker"], mc))

    caps.sort(key=lambda x: x[1], reverse=True)

    print("=" * 70)
    print("SECTION 3: MARKET CAP DISTRIBUTION")
    print("=" * 70)

    print(f"  Tickers with market_cap:    {len(caps)} / {len(has_info)}")

    if not caps:
        print("  No market cap data available.")
        print()
        return

    buckets = {"Large (>=10T)": 0, "Mid (1T-10T)": 0, "Small (100B-1T)": 0, "Micro (<100B)": 0}
    for _, mc in caps:
        if mc >= 10e12:
            buckets["Large (>=10T)"] += 1
        elif mc >= 1e12:
            buckets["Mid (1T-10T)"] += 1
        elif mc >= 100e9:
            buckets["Small (100B-1T)"] += 1
        else:
            buckets["Micro (<100B)"] += 1

    print("\n  Size distribution:")
    for label, count in buckets.items():
        pct = count / len(caps) * 100
        bar = "#" * int(pct / 2)
        print(f"    {label:<20} {count:>4} ({pct:>5.1f}%) {bar}")

    print("\n  Top 20 by market cap:")
    for ticker, mc in caps[:20]:
        print(f"    {ticker:<8} {fmt_vnd(mc):>20}")

    print("\n  Bottom 10 by market cap:")
    for ticker, mc in caps[-10:]:
        print(f"    {ticker:<8} {fmt_vnd(mc):>20}")

    print()


# ── Section 4: Shareholder & Officer Analysis ───────────────────────────────

def section_shareholders(data: list[dict]):
    has_info = [d for d in data if d.get("company_info")]

    shareholder_counts = []
    officer_counts = []
    top_shareholders = Counter()
    insider_ownership = []

    for d in has_info:
        ci = d["company_info"]
        shareholders = ci.get("shareholders", [])
        officers = ci.get("officers", [])
        shareholder_counts.append((d["ticker"], len(shareholders)))
        officer_counts.append((d["ticker"], len(officers)))

        total_pct = sum(s["percentage"] for s in shareholders)
        if total_pct > 0:
            insider_ownership.append((d["ticker"], total_pct))

        for s in shareholders:
            top_shareholders[s["name"]] += 1

    print("=" * 70)
    print("SECTION 4: SHAREHOLDER & OFFICER ANALYSIS")
    print("=" * 70)

    sc = [c for _, c in shareholder_counts]
    oc = [c for _, c in officer_counts]

    print("\n  Shareholders per ticker:")
    print(f"    Min: {min(sc)}  |  Max: {max(sc)}  |  Avg: {sum(sc)/len(sc):.1f}")

    print("\n  Officers per ticker:")
    print(f"    Min: {min(oc)}  |  Max: {max(oc)}  |  Avg: {sum(oc)/len(oc):.1f}")

    print("\n  Top 15 most frequent shareholders (appear across tickers):")
    for name, count in top_shareholders.most_common(15):
        print(f"    {name:<55} {count:>3} tickers")

    if insider_ownership:
        insider_ownership.sort(key=lambda x: x[1], reverse=True)
        print("\n  Top 15 highest disclosed ownership concentration:")
        for ticker, total_pct in insider_ownership[:15]:
            print(f"    {ticker:<8} {fmt_pct(total_pct):>10} disclosed")
        print("\n  Lowest ownership concentration:")
        for ticker, total_pct in insider_ownership[-10:]:
            print(f"    {ticker:<8} {fmt_pct(total_pct):>10} disclosed")

    print()


# ── Section 5: Financial Ratios Analysis ─────────────────────────────────────

def section_financial_ratios(data: list[dict]):
    has_ratios = [d for d in data if d.get("financial_ratios")]

    print("=" * 70)
    print("SECTION 5: FINANCIAL RATIOS ANALYSIS")
    print("=" * 70)

    print(f"  Tickers with financial_ratios: {len(has_ratios)}")

    ratio_counts = []
    years_available = Counter()
    latest_pe = []
    latest_roe = []
    latest_revenue = []
    latest_net_profit = []
    latest_revenue_growth = []
    latest_net_profit_growth = []

    for d in has_ratios:
        ratios = d["financial_ratios"]
        ratio_counts.append(len(ratios))

        if ratios:
            latest = ratios[0]
            years_available[latest.get("yearReport", "N/A")] += 1

            pe = latest.get("pe")
            if pe and pe > 0:
                latest_pe.append((d["ticker"], pe))

            roe = latest.get("roe")
            if roe:
                latest_roe.append((d["ticker"], roe))

            rev = latest.get("revenue")
            if rev:
                latest_revenue.append((d["ticker"], rev))

            np = latest.get("netProfit")
            if np:
                latest_net_profit.append((d["ticker"], np))

            rg = latest.get("revenueGrowth")
            if rg is not None:
                latest_revenue_growth.append((d["ticker"], rg))

            ng = latest.get("netProfitGrowth")
            if ng is not None:
                latest_net_profit_growth.append((d["ticker"], ng))

    print("\n  Ratio entries per ticker:")
    print(f"    Min: {min(ratio_counts)}  |  Max: {max(ratio_counts)}  |  Avg: {sum(ratio_counts)/len(ratio_counts):.1f}")

    print("\n  Year reports distribution (latest period):")
    for yr, count in sorted(years_available.items(), reverse=True):
        print(f"    {yr}: {count} tickers")

    # PE Analysis
    if latest_pe:
        latest_pe.sort(key=lambda x: x[1])
        print("\n  PE Ratio (latest, positive only):")
        print(f"    Tickers with PE: {len(latest_pe)}")
        pes = [pe for _, pe in latest_pe]
        print(f"    Min: {min(pes):.1f}  |  Max: {max(pes):.1f}  |  Median: {sorted(pes)[len(pes)//2]:.1f}")
        print("\n    Lowest PE (potentially undervalued):")
        for t, pe in latest_pe[:10]:
            print(f"      {t:<8} PE: {pe:.1f}")
        print("\n    Highest PE (growth premium):")
        for t, pe in latest_pe[-10:]:
            print(f"      {t:<8} PE: {pe:.1f}")

    # ROE Analysis
    if latest_roe:
        latest_roe.sort(key=lambda x: x[1], reverse=True)
        print("\n  ROE (latest):")
        print(f"    Tickers with ROE: {len(latest_roe)}")
        roes = [r for _, r in latest_roe]
        print(f"    Min: {min(roes)*100:.1f}%  |  Max: {max(roes)*100:.1f}%  |  Median: {sorted(roes)[len(roes)//2]*100:.1f}%")
        print("\n    Top 15 ROE:")
        for t, roe in latest_roe[:15]:
            print(f"      {t:<8} ROE: {fmt_pct(roe)}")

    # Revenue
    if latest_revenue:
        latest_revenue.sort(key=lambda x: x[1], reverse=True)
        print("\n  Revenue (latest period, top 15):")
        for t, rev in latest_revenue[:15]:
            print(f"    {t:<8} {fmt_vnd(rev)}")

    # Revenue Growth
    if latest_revenue_growth:
        latest_revenue_growth.sort(key=lambda x: x[1], reverse=True)
        print("\n  Revenue Growth (latest, top 15):")
        for t, rg in latest_revenue_growth[:15]:
            print(f"    {t:<8} {fmt_pct(rg)}")
        print("\n  Revenue Decline (worst 10):")
        for t, rg in latest_revenue_growth[-10:]:
            print(f"    {t:<8} {fmt_pct(rg)}")

    # Net Profit Growth
    if latest_net_profit_growth:
        latest_net_profit_growth.sort(key=lambda x: x[1], reverse=True)
        print("\n  Net Profit Growth (latest, top 15):")
        for t, ng in latest_net_profit_growth[:15]:
            print(f"    {t:<8} {fmt_pct(ng)}")
        print("\n  Net Profit Decline (worst 10):")
        for t, ng in latest_net_profit_growth[-10:]:
            print(f"    {t:<8} {fmt_pct(ng)}")

    print()


# ── Section 6: Data Quality Checks ──────────────────────────────────────────

def section_data_quality(data: list[dict]):
    print("=" * 70)
    print("SECTION 6: DATA QUALITY CHECKS")
    print("=" * 70)

    issues: dict[str, list[str]] = defaultdict(list)

    for d in data:
        ticker = d["ticker"]
        ci = d.get("company_info")
        ratios = d.get("financial_ratios", [])

        if not ci:
            issues["No company_info"].append(ticker)
            continue

        if not ci.get("exchange"):
            issues["Missing exchange"].append(ticker)
        if not ci.get("industry"):
            issues["Missing industry"].append(ticker)
        if not ci.get("market_cap"):
            issues["Missing market_cap"].append(ticker)
        if not ci.get("outstanding_shares"):
            issues["Missing outstanding_shares"].append(ticker)
        if not ci.get("shareholders"):
            issues["No shareholders"].append(ticker)
        if not ci.get("officers"):
            issues["No officers"].append(ticker)
        if ci.get("company_profile") and "<div" in (ci.get("company_profile") or ""):
            pass  # expected HTML
        elif not ci.get("company_profile"):
            issues["Missing company_profile"].append(ticker)

        if not ratios:
            issues["No financial_ratios"].append(ticker)
            continue

        latest = ratios[0]
        expected_keys = ["pe", "roe", "roa", "eps", "revenue", "netProfit", "yearReport", "ticker"]
        for key in expected_keys:
            if key not in latest:
                issues[f"Missing ratio key '{key}' in latest"].append(ticker)

        for i, r in enumerate(ratios):
            if r.get("ticker") != ticker:
                issues[f"Ratio ticker mismatch (ratio[{i}])"].append(
                    f"{ticker} -> {r.get('ticker')}"
                )

        for r in ratios:
            pe = r.get("pe")
            if pe is not None and pe <= 0:
                issues["Negative/zero PE"].append(f"{ticker} (PE={pe:.1f})")
                break

    print("\n  Issues found:")
    if not issues:
        print("    No issues detected!")
    else:
        for issue_type, tickers in sorted(issues.items()):
            count = len(tickers)
            print(f"\n    {issue_type} ({count}):")
            sample = tickers[:10]
            for t in sample:
                print(f"      - {t}")
            if count > 10:
                print(f"      ... and {count - 10} more")

    print()


# ── Section 7: Cross-Ticker Comparison Table ────────────────────────────────

def section_comparison_table(data: list[dict]):
    has_full = [d for d in data if d.get("company_info") and d.get("financial_ratios")]

    print("=" * 70)
    print("SECTION 7: SUMMARY TABLE (latest ratios, top 30 by market cap)")
    print("=" * 70)

    rows = []
    for d in has_full:
        ci = d["company_info"]
        ratios = d["financial_ratios"]
        if not ratios:
            continue
        r = ratios[0]
        rows.append({
            "ticker": d["ticker"],
            "exchange": ci.get("exchange", ""),
            "industry": (ci.get("industry") or "")[:30],
            "market_cap": ci.get("market_cap", 0),
            "pe": r.get("pe"),
            "pb": r.get("pb"),
            "roe": r.get("roe"),
            "roa": r.get("roa"),
            "revenue_growth": r.get("revenueGrowth"),
            "net_profit_growth": r.get("netProfitGrowth"),
            "de": r.get("de"),
            "current_ratio": r.get("currentRatio"),
        })

    rows.sort(key=lambda x: x["market_cap"] or 0, reverse=True)

    header = f"  {'Ticker':<7} {'Exch':<5} {'PE':>7} {'PB':>6} {'ROE':>7} {'D/E':>6} {'RevGr':>7} {'NPGr':>7}"
    print(header)
    print("  " + "-" * (len(header) - 2))

    for r in rows[:30]:
        pe = f"{r['pe']:.1f}" if r['pe'] else "N/A"
        pb = f"{r['pb']:.2f}" if r['pb'] else "N/A"
        roe = f"{r['roe']*100:.1f}%" if r['roe'] else "N/A"
        de = f"{r['de']:.2f}" if r['de'] else "N/A"
        rg = f"{r['revenue_growth']*100:.1f}%" if r['revenue_growth'] is not None else "N/A"
        ng = f"{r['net_profit_growth']*100:.1f}%" if r['net_profit_growth'] is not None else "N/A"
        print(f"  {r['ticker']:<7} {r['exchange']:<5} {pe:>7} {pb:>6} {roe:>7} {de:>6} {rg:>7} {ng:>7}")

    print()


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    default_path = str(Path(__file__).resolve().parent.parent / "aipriceaction" / "company_info.json")
    path = sys.argv[1] if len(sys.argv) > 1 else default_path

    print(f"\nLoading: {path}")
    data = load_data(path)
    print(f"Loaded {len(data)} entries\n")

    section_overview(data)
    section_exchange_industry(data)
    section_market_cap(data)
    section_shareholders(data)
    section_financial_ratios(data)
    section_data_quality(data)
    section_comparison_table(data)

    print("=" * 70)
    print("Analysis complete.")
    print("=" * 70)


if __name__ == "__main__":
    main()
