name: "AIPriceAction Weekly Report"

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

  # Sets up a scheduled run
  schedule:
    # Runs at 20:00 UTC on Friday.
    # Format is: Minute Hour Day(month) Month Day(week)
    - cron: "0 20 * * 5"

# Grant write permissions to the GITHUB_TOKEN to allow the workflow to commit and push changes.
permissions:
  contents: write

jobs:
  generate-report:
    runs-on: ubuntu-latest
    name: Generate Weekly Market Report

    steps:
      # Step 1: Check out the repository code so the workflow can access it.
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up the specific version of Python you are using.
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      # Step 3: Install the required Python libraries from your requirements file.
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Backup market data and clean up reports before the new run.
      - name: Backup market data and clean up reports
        run: |
          # Remove old backup directory if it exists
          rm -rf market_data_week_backup
          # Create directories if they don't exist to prevent errors on the first run.
          mkdir -p market_data_week reports_week
          # Move existing market data to backup for dividend detection
          if [ -d "market_data_week" ] && [ "$(ls -A market_data_week)" ]; then
            mv market_data_week market_data_week_backup
            mkdir market_data_week
            echo "Moved market_data_week to market_data_week_backup"
          fi
          # Remove the old reports directory to clear out stale charts.
          rm -rf reports_week/*

      # Step 5: Check for dividend adjustments
      - name: Check for dividend adjustments
        run: |
          if [ -d "market_data_check_dividends_week" ] && [ "$(ls -A market_data_check_dividends_week)" ]; then
            echo "Dividend adjustments detected for weekly data"
            # Add dividend processing logic here if needed
          else
            echo "No dividend adjustments needed for weekly data"
          fi

      # Step 8: Run the main Python script to generate the new files.
      - name: Run data pipeline and generate report
        run: python main.py --week --check-dividend

      # Step 10: Combine only the last 40 lines of each market data file.
      - name: Combine last 40 lines of market data
        run: |
          cd market_data_week
          tail_output_file="market_data_week.txt"

          if [ -f "$tail_output_file" ]; then
              rm "$tail_output_file"
          fi

          for file in *; do
              # Ensure that we are only processing files and not the output file itself.
              if [ -f "$file" ] && [ "$file" != "$tail_output_file" ]; then
                  full_path=$(pwd)/"$file"
                  echo "// $full_path" >> "$tail_output_file"
                  tail -n 40 "$file" >> "$tail_output_file"
                  echo "" >> "$tail_output_file"
              fi
          done

          echo "Last 40 lines of each file have been combined into $tail_output_file"

      # Step 11: Commit and push the updated report, data, and charts to the repository.
      - name: Commit and push changes
        run: |
          # Configure git with the details of the last commit's author to keep authorship consistent.
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

          # Add all new/changed files to the staging area.
          git add .

          # Check if there are any changes to commit. If not, exit successfully.
          if git diff-index --quiet HEAD; then
            echo "No changes to commit. Exiting."
            exit 0
          fi

          # Amend the last commit to avoid polluting the git history with weekly update commits.
          git commit --amend --no-edit

          # Force push the amended commit to the repository.
          # --force-with-lease is a safer alternative to a standard --force.
          git push --force-with-lease

